// Client bootstrap .ps1 generator for the SANDBOX.
//
// The sandbox uses a self-signed certificate, which winget refuses until the
// device trusts the CA -- a chicken-and-egg for clients (you cannot fetch the CA
// over the trusted HTTPS channel before you trust it). This script breaks that:
// it is served over PLAIN HTTP (so it downloads with no cert trust needed) and,
// when run elevated on a client, it (1) trusts the embedded sandbox CA into the
// machine Trusted Root store, (2) registers the private WinGet REST source, and
// (3) maps ONLY the RepoFabric source + installer URLs (scheme + host + PORT) to
// the Intranet Zone via the Site to Zone Assignment List, so winget does not
// stall applying Mark-of-the-Web to installers from this reputation-less,
// self-signed, non-standard-port host. Every other download keeps full protection.
//
// Why the Intranet Zone, and why the full URL with port: winget's
// Mark-of-the-Web step (IAttachmentExecute) crashes on files tagged from the
// Internet zone by this host. The per-host Trusted Sites map keys on hostname only
// and treats a non-standard port (here :8443) as the Internet zone, so it does NOT
// help. The Site to Zone Assignment List keys on the full URL (port included) and
// the Intranet Zone is the low-risk zone whose downloads skip the attachment
// scan, so mapping the exact site there is what lets winget proceed.
//
// TRIAL-ONLY: it is fetched over plain HTTP and run via `irm ... | iex`, so it is a
// throwaway-sandbox quick-start. For real fleets, onboard clients with the no-iex
// GPO/Intune scripts (clientconfig.js / intunepolicyscript.js) over trusted HTTPS.
// (`irm`/`iex` are PowerShell cmdlets, unrelated to Internet Explorer; MSIE being
// retired does not affect them.)
//
// Usage on a client (elevated PowerShell):
//   irm http://<host>:<http-port>/setup.ps1 | iex

// Escape a value for a PowerShell single-quoted literal (' -> '').
function psq(s) { return String(s == null ? '' : s).replace(/'/g, "''"); }

// Site origin (scheme://host[:port]) of a URL, or '' if empty/unparseable. The port
// is included when non-default, which is exactly what the Site to Zone list needs to
// scope a non-standard-port sandbox host. On a standard 443 host the port is omitted.
function originOf(u) { try { const x = new URL(String(u)); return x.protocol + '//' + x.host; } catch { return ''; } }

export function buildClientBootstrapScript({ sourceName, sourceUrl, installerUrl, caPem } = {}) {
  const name = String(sourceName || 'repofabric-main');
  const url  = String(sourceUrl || '');
  // Trim and normalise the CA to LF so the here-string is clean; the file is
  // written back with ascii encoding which Import-Certificate accepts (PEM).
  const ca   = String(caPem || '').replace(/\r\n/g, '\n').trim();

  // RepoFabric sites to map into the Intranet Zone: the source/API site and
  // the installer site (often different subdomains), each as scheme://host:port.
  // De-duplicated; installerUrl may be absent (older callers), in which case only
  // the source site is mapped.
  const rfSites = [...new Set([originOf(url), originOf(installerUrl)].filter(Boolean))];
  const psSiteArray = rfSites.map(s => `'${psq(s)}'`).join(', ');

  const lines = [
    '#requires -Version 5.1',
    '#requires -RunAsAdministrator',
    '<#',
    '.SYNOPSIS',
    '    RepoFabric Sandbox client bootstrap. Trusts the sandbox self-signed CA,',
    '    registers the private WinGet REST source, and maps the RepoFabric site(s) to',
    '    the Intranet Zone (port-aware) so large installs do not stall. Run ELEVATED.',
    '    Generated by RepoFabric (RingoSystems Heavy Industries). Safe to re-run.',
    '    TRIAL-ONLY quick-start (plain HTTP + iex); fleets onboard via GPO/Intune.',
    '#>',
    "$ErrorActionPreference = 'Stop'",
    '',
    '# 1) Trust the sandbox CA (embedded below, so no separate download is needed).',
    "$caPem = @'",
    ca,
    "'@",
    "$caFile = Join-Path $env:TEMP 'repofabric-sandbox-ca.crt'",
    'Set-Content -Path $caFile -Value $caPem -Encoding ascii',
    'Import-Certificate -FilePath $caFile -CertStoreLocation Cert:\\LocalMachine\\Root | Out-Null',
    'Remove-Item $caFile -ErrorAction SilentlyContinue',
    "Write-Host 'Trusted the RepoFabric Sandbox CA (LocalMachine\\Root).' -ForegroundColor Green",
    '',
    '# 2) Register the private WinGet REST source (clears any prior broken entry first).',
    `$src = '${psq(name)}'`,
    `$url = '${psq(url)}'`,
    'winget source remove --name $src 2>$null | Out-Null',
    'winget source add --name $src --arg $url --type Microsoft.Rest',
    'Write-Host "Registered WinGet source \'$src\' -> $url" -ForegroundColor Green',
    '',
    '# 3) Map ONLY the RepoFabric site(s) into the Intranet Zone, scoped to the',
    '#    exact scheme + host + PORT via the Site to Zone Assignment List (ZoneMapKey).',
    "#    winget stalls in its Mark-of-the-Web step on installers from this self-signed,",
    '#    reputation-less host. The per-host Trusted Sites map keys on hostname only and',
    '#    treats the non-standard :8443 port as the Internet zone, so it does NOT fix it.',
    '#    Mapping the full URL (with port) to the Intranet Zone (1), the low-risk',
    '#    zone whose downloads skip the attachment scan, is what lets winget proceed.',
    '#    Every OTHER download keeps full Mark-of-the-Web protection. Not needed in',
    '#    production on a standard-443 host.',
    `$rfSites = @(${psSiteArray})`,
    "$zmk = 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\ZoneMapKey'",
    'New-Item -Path $zmk -Force | Out-Null',
    'foreach ($s in $rfSites) {',
    "  New-ItemProperty -Path $zmk -Name $s -Value '1' -PropertyType String -Force | Out-Null",
    '  Write-Host "Trusted $s for winget downloads (Intranet Zone)." -ForegroundColor Green',
    '}',
    "# Clear winget's download cache so the next install fetches a fresh download under",
    '# the new zone mapping (a previously Internet-zone-tagged cached file would persist).',
    "Remove-Item (Join-Path $env:LOCALAPPDATA 'Temp\\WinGet') -Recurse -Force -ErrorAction SilentlyContinue",
    `Write-Host 'Done. Install apps with:  winget install --source ${psq(name)} --id <PackageId>' -ForegroundColor Cyan`,
    '',
  ];
  // Windows-friendly CRLF line endings.
  return lines.join('\r\n');
}
