// peercachediag.js: generate a standalone, READ-ONLY PowerShell 5/7 diagnostic
// that proves whether installer bytes are actually being served by LAN peers
// (BranchCache / BITS / Delivery Optimization) versus pulled from the origin
// server. One per winget repo so the optional live A/B test targets the right
// source.
//
// Why this exists: the server (winget source / installer host) can only ever
// observe its OWN egress. Peer-to-peer transfers happen LAN-side and never
// touch the server, so "are we actually saving bandwidth" can only be answered
// on the CLIENTS. This script reads the client-side counters that carry the
// ground truth:
//   * BranchCache retrieval counters  -> Bytes from Server vs Bytes from Cache
//     (cache == local/peer-sourced) and Bytes Served (fed to other peers).
//   * Delivery Optimization perf snap + per-file status -> BytesFromPeers vs
//     BytesFromHttp vs BytesFromCacheServer, i.e. exactly where each file's
//     bits came from.
//
// With -TestPackageId it snapshots the counters, installs (or downloads) that
// package FROM the repo's private source, snapshots again, and reports the
// per-source byte breakdown for that single download plus a savings verdict.
// Read-only unless -TestPackageId is supplied.

function psSingleQuote(value) {
  const s = String(value ?? '');
  if (/[\r\n\0]/.test(s)) throw new Error(`value contains illegal control characters: ${JSON.stringify(s)}`);
  return "'" + s.replace(/'/g, "''") + "'";
}

function psComment(value) {
  return String(value ?? '').replace(/[\r\n\0]+/g, ' ').replace(/#>/g, '# >');
}

export function peerCacheDiagFilename(repo) {
  const id = String(repo?.RepoId || repo?.repoId || 'repo')
    .replace(/[^A-Za-z0-9._-]+/g, '-').replace(/^-+|-+$/g, '');
  return `Test-RfPeerCache-${id || 'repo'}.ps1`;
}

// opts: { repo, sourceName }
export function buildPeerCacheDiagScript(opts = {}) {
  const repo = opts.repo || {};
  const repoId = String(repo.RepoId || repo.repoId || 'repo');
  const displayName = psComment(repo.DisplayName || repo.displayName || repoId);
  const sourceName = opts.sourceName || 'repofabric';
  const q = psSingleQuote;

  const L = [];
  L.push('#requires -Version 5.1');
  L.push('<#');
  L.push('.SYNOPSIS');
  L.push(`    RepoFabric peer-cache diagnostic for the winget repo "${displayName}".`);
  L.push('    Generated by RepoFabric (RingoSystems Heavy Industries). Windows PowerShell 5.1 and 7+.');
  L.push('.DESCRIPTION');
  L.push('    READ-ONLY by default. Reports BranchCache, BITS Peercaching and');
  L.push('    Delivery Optimization state plus the counters that show where');
  L.push('    installer bytes came from (LAN peers / local cache vs origin server).');
  L.push('    Run on two or more clients on the SAME subnet to confirm savings:');
  L.push('    the first device pulls from the server, later devices should pull');
  L.push('    from peers.');
  L.push('.PARAMETER TestPackageId');
  L.push('    Optional. A winget package Id to actually download from this repo');
  L.push('    source NOW, measuring the per-source byte split for that one');
  L.push('    download. Installs the package (machine scope, needs elevation)');
  L.push('    unless -DownloadOnly is given.');
  L.push('.PARAMETER DownloadOnly');
  L.push('    With -TestPackageId, use "winget download" instead of installing.');
  L.push('.EXAMPLE');
  L.push(`    .\\${peerCacheDiagFilename(repo)}`);
  L.push('.EXAMPLE');
  L.push(`    .\\${peerCacheDiagFilename(repo)} -TestPackageId Adobe.Acrobat.Reader.64-bit`);
  L.push('#>');
  L.push('[CmdletBinding()]');
  L.push('param(');
  L.push(`  [string]$SourceName = ${q(sourceName)},`);
  L.push('  [string]$TestPackageId,');
  L.push('  [switch]$DownloadOnly,');
  L.push('  [string]$DownloadPath = (Join-Path $env:TEMP "RfPeerTest")');
  L.push(')');
  L.push('');
  L.push("$ErrorActionPreference = 'Continue'");
  L.push('function Write-Head { param([string]$m) Write-Host ""; Write-Host ("=== " + $m + " ===") -ForegroundColor Cyan }');
  L.push('function Write-Ok   { param([string]$m) Write-Host ("  [ok] "   + $m) -ForegroundColor Green }');
  L.push('function Write-Info { param([string]$m) Write-Host ("  "        + $m) }');
  L.push('function Write-Warn { param([string]$m) Write-Host ("  [warn] " + $m) -ForegroundColor Yellow }');
  L.push('function Fmt-Bytes { param([double]$b)');
  L.push('  if ($b -ge 1GB) { return ("{0:N2} GB" -f ($b/1GB)) }');
  L.push('  if ($b -ge 1MB) { return ("{0:N2} MB" -f ($b/1MB)) }');
  L.push('  if ($b -ge 1KB) { return ("{0:N1} KB" -f ($b/1KB)) }');
  L.push('  return ("{0} B" -f [int64]$b) }');
  L.push('');

  // BranchCache counter reader (localization-tolerant: match by path substring).
  L.push('# BranchCache retrieval counters. "From Cache" = bytes sourced from the');
  L.push('# local/peer BranchCache; "From Server" = bytes pulled from origin;');
  L.push('# "Served" = bytes this host handed to other peers. Matched by path');
  L.push('# substring so it survives counter localization on English builds.');
  L.push('function Get-RfBCCounters {');
  L.push('  $o = [pscustomobject]@{ FromServer = $null; FromCache = $null; Served = $null }');
  L.push('  try {');
  L.push("    $samples = (Get-Counter '\\BranchCache\\*' -ErrorAction Stop).CounterSamples");
  L.push('    foreach ($s in $samples) {');
  L.push('      $p = $s.Path.ToLower()');
  L.push("      if     ($p -match 'bytes from server') { $o.FromServer = [int64]$s.CookedValue }");
  L.push("      elseif ($p -match 'bytes from cache')  { $o.FromCache  = [int64]$s.CookedValue }");
  L.push("      elseif ($p -match 'bytes served')      { $o.Served     = [int64]$s.CookedValue }");
  L.push('    }');
  L.push('  } catch { }');
  L.push('  return $o');
  L.push('}');
  L.push('');
  L.push('$elevated = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator)');
  L.push('Write-Head ("RepoFabric peer-cache diagnostic  (host " + $env:COMPUTERNAME + ", source " + $SourceName + ")")');
  L.push('Write-Info ("PowerShell " + $PSVersionTable.PSVersion + " | elevated: " + $elevated)');
  L.push('');

  // Policy / posture section.
  L.push('Write-Head "Peer-caching posture (policy)"');
  L.push('$bitsKey = "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\BITS"');
  L.push('$doKey   = "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\DeliveryOptimization"');
  L.push('$bitsPeer = (Get-ItemProperty -Path $bitsKey -Name EnablePeerCaching -ErrorAction SilentlyContinue).EnablePeerCaching');
  L.push('$doMode   = (Get-ItemProperty -Path $doKey   -Name DODownloadMode   -ErrorAction SilentlyContinue).DODownloadMode');
  L.push('Write-Info ("BITS EnablePeerCaching : " + $(if ($null -ne $bitsPeer) { $bitsPeer } else { "<not set>" }))');
  L.push('Write-Info ("DO DODownloadMode      : " + $(if ($null -ne $doMode)   { $doMode }   else { "<not set>" }) + "  (1 = LAN peers)")');
  L.push('if ($bitsPeer -ne 1 -and $doMode -ne 1 -and $doMode -ne 2) { Write-Warn "Neither BITS peer caching nor DO LAN mode is enabled by policy; run the Client config .ps1 first." }');
  L.push('');

  // BranchCache section.
  L.push('Write-Head "BranchCache"');
  L.push('try {');
  L.push('  $bc = Get-BCStatus -ErrorAction Stop');
  L.push('  Write-Info ("Enabled        : " + $bc.BranchCacheServiceStatus + " / serviceMode=" + $bc.ClientConfiguration.CurrentClientMode)');
  L.push('  Write-Info ("Distributed    : " + $bc.ClientConfiguration.CurrentClientMode)');
  L.push('} catch { Write-Warn ("Get-BCStatus unavailable: " + $_.Exception.Message + " (BranchCache feature may be off)") }');
  L.push('try {');
  L.push('  $cache = Get-BCDataCache -ErrorAction Stop');
  L.push('  Write-Info ("Data cache used : " + (Fmt-Bytes $cache.CurrentActiveCacheSize) + " of " + (Fmt-Bytes $cache.MaxCacheSizeAsNumberOfBytes))');
  L.push('  if ($cache.CurrentActiveCacheSize -gt 0) { Write-Ok "This host has cached content it can serve to peers." }');
  L.push('} catch { }');
  L.push('$c = Get-RfBCCounters');
  L.push('if ($c.FromServer -ne $null -or $c.FromCache -ne $null) {');
  L.push('  Write-Info ("Retrieval: from server = " + (Fmt-Bytes ([double]($c.FromServer))) + " | from cache/peers = " + (Fmt-Bytes ([double]($c.FromCache))) + " | served to peers = " + (Fmt-Bytes ([double]($c.Served))))');
  L.push('  $tot = [double]$c.FromServer + [double]$c.FromCache');
  L.push('  if ($tot -gt 0) { Write-Info ("Lifetime peer/cache share: {0:P1}" -f ([double]$c.FromCache / $tot)) }');
  L.push('} else { Write-Warn "BranchCache retrieval counters not present (no BranchCache traffic yet, or non-English counter names)." }');
  L.push('');

  // Delivery Optimization section.
  L.push('Write-Head "Delivery Optimization"');
  L.push('try {');
  L.push('  $snap = Get-DeliveryOptimizationPerfSnap -ErrorAction Stop');
  L.push('  $peers = [double]($snap.BytesFromPeers); $http = [double]($snap.BytesFromHttp); $cdn = [double]($snap.BytesFromCacheServer)');
  L.push('  Write-Info ("Bytes from peers       : " + (Fmt-Bytes $peers))');
  L.push('  Write-Info ("Bytes from HTTP/origin : " + (Fmt-Bytes $http))');
  L.push('  Write-Info ("Bytes from cache server: " + (Fmt-Bytes $cdn))');
  L.push('  $dt = $peers + $http + $cdn');
  L.push('  if ($dt -gt 0) { Write-Info ("DO peer share: {0:P1}" -f ($peers / $dt)) }');
  L.push('} catch { Write-Warn ("Get-DeliveryOptimizationPerfSnap unavailable: " + $_.Exception.Message) }');
  L.push('try {');
  L.push('  $do = Get-DeliveryOptimizationStatus -ErrorAction Stop | Where-Object { $_.FileSize -gt 0 }');
  L.push('  if ($do) {');
  L.push('    Write-Info "Recent files (where the bits came from):"');
  L.push('    $do | Sort-Object -Property BytesFromPeers -Descending | Select-Object -First 15 |');
  L.push('      Format-Table -AutoSize @{n="File";e={ if ($_.FileId) { ($_.FileId.ToString()).Substring(0,[Math]::Min(18,$_.FileId.ToString().Length)) } else { "-" } }},');
  L.push('        @{n="Size";e={ Fmt-Bytes $_.FileSize }},');
  L.push('        @{n="Peers";e={ Fmt-Bytes ([double]$_.BytesFromPeers) }},');
  L.push('        @{n="HTTP";e={ Fmt-Bytes ([double]$_.BytesFromHttp) }},');
  L.push('        @{n="CacheSrv";e={ Fmt-Bytes ([double]$_.BytesFromCacheServer) }} | Out-Host');
  L.push('  } else { Write-Info "No Delivery Optimization file activity recorded yet." }');
  L.push('} catch { }');
  L.push('');

  // Optional live test.
  L.push('# --- Optional live A/B download test --------------------------------------');
  L.push('if ($TestPackageId) {');
  L.push('  Write-Head ("Live test: pulling " + $TestPackageId + " from " + $SourceName)');
  L.push('  if (-not $DownloadOnly -and -not $elevated) { Write-Warn "Installing needs elevation; re-run as Administrator or add -DownloadOnly." }');
  L.push('  $winget = Get-Command winget.exe -ErrorAction SilentlyContinue');
  L.push('  if (-not $winget) { Write-Warn "winget.exe not found; skipping live test." }');
  L.push('  else {');
  L.push('    $bcBefore = Get-RfBCCounters');
  L.push('    try { $doBefore = Get-DeliveryOptimizationPerfSnap -ErrorAction Stop } catch { $doBefore = $null }');
  L.push('    $started = Get-Date');
  L.push('    if ($DownloadOnly) {');
  L.push('      New-Item -ItemType Directory -Force -Path $DownloadPath | Out-Null');
  L.push('      & winget.exe download --id $TestPackageId --source $SourceName --accept-package-agreements --accept-source-agreements --disable-interactivity -d $DownloadPath');
  L.push('    } else {');
  L.push('      & winget.exe install --id $TestPackageId --source $SourceName --silent --accept-package-agreements --accept-source-agreements --disable-interactivity --scope machine --exact');
  L.push('    }');
  L.push('    $wingetExit = $LASTEXITCODE');
  L.push('    Start-Sleep -Seconds 3');
  L.push('    $bcAfter = Get-RfBCCounters');
  L.push('    try { $doAfter = Get-DeliveryOptimizationPerfSnap -ErrorAction Stop } catch { $doAfter = $null }');
  L.push('    $dSrv = [double]$bcAfter.FromServer - [double]$bcBefore.FromServer');
  L.push('    $dCac = [double]$bcAfter.FromCache  - [double]$bcBefore.FromCache');
  L.push('    $dSrvd= [double]$bcAfter.Served     - [double]$bcBefore.Served');
  L.push('    $dp = 0; $dh = 0');
  L.push('    Write-Head "Where THIS download came from"');
  L.push('    Write-Info ("Elapsed: {0:N1}s" -f ((Get-Date) - $started).TotalSeconds)');
  L.push('    Write-Info ("BranchCache  from origin server : " + (Fmt-Bytes $dSrv))');
  L.push('    Write-Info ("BranchCache  from cache/peers    : " + (Fmt-Bytes $dCac))');
  L.push('    Write-Info ("BranchCache  served to peers     : " + (Fmt-Bytes $dSrvd))');
  L.push('    if ($doBefore -and $doAfter) {');
  L.push('      $dp = [double]$doAfter.BytesFromPeers - [double]$doBefore.BytesFromPeers');
  L.push('      $dh = [double]$doAfter.BytesFromHttp  - [double]$doBefore.BytesFromHttp');
  L.push('      Write-Info ("DeliveryOpt  from peers          : " + (Fmt-Bytes $dp))');
  L.push('      Write-Info ("DeliveryOpt  from HTTP/origin     : " + (Fmt-Bytes $dh))');
  L.push('    }');
  L.push('    # Combine BOTH transports: BranchCache (from cache/peers vs server)');
  L.push('    # and Delivery Optimization (from peers vs HTTP). DO is usually the');
  L.push('    # one that actually carries winget installer bytes, so the verdict must');
  L.push('    # not rely on BranchCache counters alone.');
  L.push('    $peerBytes   = [Math]::Max(0, $dCac) + [Math]::Max(0, $dp)');
  L.push('    $originBytes = [Math]::Max(0, $dSrv) + [Math]::Max(0, $dh)');
  L.push('    $sum = $peerBytes + $originBytes');
  L.push('    Write-Head "Savings verdict"');
  L.push('    if ($wingetExit -ne 0) {');
  L.push('      Write-Warn ("Test download did NOT succeed (winget exit " + $wingetExit + "). The error above means \"" + $TestPackageId + "\" is not served by " + $SourceName + ", or the source could not be queried (e.g. 0x8a150044 = rest-endpoint-not-found). No bytes moved, so there is nothing to measure.")');
  L.push('      Write-Info "Confirm the source is healthy, then pick a package it actually serves:"');
  L.push('      & winget.exe source list --name $SourceName 2>&1 | Out-Host');
  L.push('      Write-Info "Note: package IDs are CASE-SENSITIVE against a REST source. Use the exact id from the Catalog (e.g. Microsoft.PowerShell, NOT microsoft.powershell); a wrong case returns 0x8a150044."');
  L.push('      Write-Info ("Try:  winget search <name> --source " + $SourceName + "   then re-run with the exact -TestPackageId.")');
  L.push('    } elseif ($sum -le 0) {');
  L.push('      Write-Warn "winget succeeded but no peer/server bytes were recorded via BranchCache or Delivery Optimization. The installer was most likely already cached locally on this device, or was served over a transport these counters do not cover. Re-run on a SECOND clean client after a first client installed the SAME version."');
  L.push('    } elseif ($peerBytes -gt 0) {');
  L.push('      Write-Ok ("{0:P1} of this download came from LAN peers/cache ({1} of {2}). That is bandwidth NOT pulled from the server." -f ($peerBytes/$sum), (Fmt-Bytes $peerBytes), (Fmt-Bytes $sum))');
  L.push('    } else {');
  L.push('      Write-Warn ("All " + (Fmt-Bytes $originBytes) + " came from the origin server, 0 from peers. Expected for the FIRST device on a subnet (it seeds the cache). Run this on a second device next.")');
  L.push('    }');
  L.push('  }');
  L.push('} else {');
  L.push('  Write-Head "Next step"');
  L.push('  Write-Info ("Run a live test:  .\\" + (Split-Path -Leaf $PSCommandPath) + " -TestPackageId <winget-id>")');
  L.push('  Write-Info "Do it on device #1 (seeds the cache), then on device #2 on the same subnet (should pull from the peer)."');
  L.push('}');
  L.push('');

  return L.join('\r\n');
}
