#!/usr/bin/env bash
# RepoFabric host-side bootstrap.
#
# Idempotent. Safe to re-run. Operates on a deploy host running Docker
# Engine 24+ with docker-compose v2 available as `docker compose`.
#
# What it does:
#   1. Creates the appdata and state directory trees.
#   2. Materialises the `repofabric` docker network if not present.
#   3. Drops a starter .env at deploy/.env (relative to the repo root)
#      if one does not exist yet.
#   4. Prints next-step instructions.
#
# Usage:
#   bash deploy/bootstrap.sh <state-root> [--appdata-root <appdata-root>]
#
#   <state-root>    Where repofabric-linux state lives (SQLite, config,
#                   upstream cache). Recommended on SSD.
#   --appdata-root  Where the companion stack appdata lives (gitea, rewinged,
#                   manifest tree, installer cache). Default: same as
#                   <state-root>. Recommended on bulk storage for the
#                   manifest tree and installer cache.
#
# Exits non-zero on any failure. All messages go to stderr; only the final
# next-steps block goes to stdout so the operator can pipe the output and
# grep for the instructions.

set -euo pipefail

err() { printf 'bootstrap: %s\n' "$*" >&2; }
die() { err "$*"; exit 1; }

# ----- Parse args -----------------------------------------------------------
if [[ $# -lt 1 ]]; then
    die "usage: bash deploy/bootstrap.sh <state-root> [--appdata-root <appdata-root>]"
fi
STATE_ROOT="$1"; shift
APPDATA_ROOT="$STATE_ROOT"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --appdata-root|--installers-host) APPDATA_ROOT="$2"; shift 2 ;;
        *) die "unknown argument: $1" ;;
    esac
done

# Resolve the repo root from the script's own path so the script can be
# invoked from anywhere.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/deploy/.env"
ENV_EXAMPLE="$REPO_ROOT/linux/.env.example"

err "repo root:    $REPO_ROOT"
err "state root:   $STATE_ROOT"
err "appdata root: $APPDATA_ROOT"

# ----- 1. Sanity: docker present --------------------------------------------
command -v docker >/dev/null 2>&1 || die "docker is not installed"
docker compose version >/dev/null 2>&1 || die "docker compose v2 is not installed (use the 'docker compose' subcommand, not docker-compose v1)"

# ----- 2. Make directories --------------------------------------------------
# Only a small set of host paths is needed: state and cache on fast storage,
# manifests and installers on bulk storage. The manifests and installers
# directories are written directly by the publisher inside repofabric-linux
# and read by rewinged and the installer file server.
mkdir -p \
    "$STATE_ROOT/state" \
    "$STATE_ROOT/cache" \
    "$APPDATA_ROOT/gitea" \
    "$APPDATA_ROOT/manifests" \
    "$APPDATA_ROOT/installers"

# Pin ownership to 99:100 (the nobody:users pair containers run as).
# Best-effort: skip on platforms where the host has no such uid.
if id 99 >/dev/null 2>&1; then
    chown -R 99:100 "$STATE_ROOT" "$APPDATA_ROOT" 2>/dev/null || \
        err "warning: chown 99:100 failed on $STATE_ROOT and $APPDATA_ROOT; the containers may report permission errors. Synology and TrueNAS use platform uids, see the per-platform docs."
fi

# ----- 3. Docker network ----------------------------------------------------
if docker network inspect repofabric >/dev/null 2>&1; then
    err "docker network 'repofabric' already exists"
else
    docker network create repofabric >/dev/null
    err "created docker network 'repofabric'"
fi

# ----- 4. Starter .env ------------------------------------------------------
if [[ -f "$ENV_FILE" ]]; then
    err ".env already exists at $ENV_FILE; not overwriting"
elif [[ -f "$ENV_EXAMPLE" ]]; then
    cp "$ENV_EXAMPLE" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    err "copied linux/.env.example -> .env at $ENV_FILE"
else
    cat > "$ENV_FILE" <<'EOF'
# RepoFabric .env. Copy this template, fill in the required values.
# Generated by deploy/bootstrap.sh.

# REQUIRED
REPOFABRIC_ADMIN_PUBLIC_URL=https://winget.example.com/admin
REPOFABRIC_SESSION_SECRET=__REPLACE_ME__   # openssl rand -hex 32
REPOFABRIC_ENTRA_TENANT_ID=
REPOFABRIC_ENTRA_CLIENT_ID=
REPOFABRIC_ENTRA_CLIENT_SECRET=
REPOFABRIC_GITEA_PAT=

# OPTIONAL
REPOFABRIC_SMTP_HOST=
REPOFABRIC_SMTP_PORT=25
REPOFABRIC_SMTP_FROM=
REPOFABRIC_SMTP_TO=
REPOFABRIC_SMTP_USERNAME=
REPOFABRIC_SMTP_PASSWORD=
REPOFABRIC_COOKIE_SECURE=true
EOF
    chmod 600 "$ENV_FILE"
    err "wrote starter .env at $ENV_FILE"
fi

# Pre-fill the session secret if the template still carries the
# REPLACE_ME marker. Cheap quality-of-life touch.
if grep -q 'REPOFABRIC_SESSION_SECRET=__REPLACE_ME__' "$ENV_FILE" 2>/dev/null; then
    SECRET="$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p -c 64)"
    if [[ -n "$SECRET" ]]; then
        sed -i.bak "s|REPOFABRIC_SESSION_SECRET=__REPLACE_ME__|REPOFABRIC_SESSION_SECRET=$SECRET|" "$ENV_FILE"
        rm -f "$ENV_FILE.bak"
        err "filled REPOFABRIC_SESSION_SECRET with a random 32-byte hex value"
    fi
fi

# ----- 4b. Compose path overrides -------------------------------------------
# The compose files read their host paths via ${REPOFABRIC_STATE_ROOT} and
# ${REPOFABRIC_APPDATA_ROOT} (each defaulting to the UNRAID layout, so an
# existing deploy that sets nothing is byte-identical). Pin them here to the
# paths this run just created so ANY host works. REPOFABRIC_ENV_FILE points the
# container's env_file straight at this .env, so there is NO separate copy step.
# Compose picks these up when invoked with `--env-file deploy/.env`.
sed -i '/^# >>> repofabric compose paths/,/^# <<< repofabric compose paths/d' "$ENV_FILE" 2>/dev/null || true
cat >> "$ENV_FILE" <<EOF
# >>> repofabric compose paths (written by bootstrap; consumed via --env-file)
REPOFABRIC_STATE_ROOT=$STATE_ROOT
REPOFABRIC_APPDATA_ROOT=$APPDATA_ROOT
REPOFABRIC_ENV_FILE=$ENV_FILE
# <<< repofabric compose paths
EOF
err "pinned compose paths in .env: STATE_ROOT=$STATE_ROOT APPDATA_ROOT=$APPDATA_ROOT"

# ----- 5. Print next steps --------------------------------------------------
cat <<EOF
RepoFabric host bootstrap complete.

Next steps:

All compose commands below pass --env-file deploy/.env, so the host paths and
secrets in that single file drive both stacks. (On UNRAID you may omit
--env-file; the compose defaults already match the UNRAID layout.)

1. Edit the starter .env and set the required values:
       $ENV_FILE

   The setup wizard will not finish without:
       REPOFABRIC_ADMIN_PUBLIC_URL       (your public HTTPS URL incl. /admin)
       REPOFABRIC_ENTRA_TENANT_ID
       REPOFABRIC_ENTRA_CLIENT_ID
       REPOFABRIC_ENTRA_CLIENT_SECRET
       REPOFABRIC_GITEA_PAT               (created in step 3)

   The compose path vars (REPOFABRIC_STATE_ROOT / _APPDATA_ROOT / _ENV_FILE) are
   already pinned for this host, and the container reads its secrets straight
   from this file, so there is NO separate .env copy step.

2. Bring up the companion stack (gitea and rewinged):
       cd $REPO_ROOT
       docker compose --env-file deploy/.env -f deploy/docker-compose.yml up -d

3. Open Gitea on http://<this-host>:3030, run the install wizard,
   create an admin account, create the 'winget-manifests' repo,
   and generate a 'repo:write' PAT. Paste it into .env as
   REPOFABRIC_GITEA_PAT.

4. Bring up repofabric-linux itself:
       docker compose --env-file deploy/.env -f linux/docker-compose.yml up -d --build repofabric-linux
       docker compose --env-file deploy/.env -f linux/docker-compose.yml logs --tail=80 repofabric-linux

   The log prints a one-time setup token inside a boxed
   "RepoFabric ... first-run setup" banner; copy the token line.

5. Configure your reverse proxy (Nginx Proxy Manager is documented at
   /docs/reverse-proxy-npm) so https://winget.<your-domain>/setup/
   reaches repofabric-linux:8086.

6. Open https://winget.<your-domain>/setup/, paste the token, walk
   the wizard.

Full deployment docs are served by the admin once it is up at
http://<this-host>:8086/docs/ (no auth required for docs).
EOF
